### ISSUE TITLE
Error when using use ctx = openContext()

### ISSUE THREAD

**Issue by Qaysi-M** [JordanMarr/SqlHydra#18]
I am trying to connect to a PostgreSQL database. Here is my code 

 ```
let openContext () =
      let compiler = SqlKata.Compilers.PostgresCompiler()
      let conn = new Npgsql.NpgsqlConnection(Helpers.connStr)
      conn.Open()
      new QueryContext(conn, compiler)
  
  let getPerson name =
      use ctx = openContext() // this line is important
      select {
          for person in Table.person do 
          where (person.name = name)
          select (person.name)
      }
      |> ctx.ReadAsync MyDb.HydraReader.Read
      |> Async.AwaitTask
      |> Async.map(Seq.exactlyOne)
```

If I do, ` use ctx =  openContext()` i get the bellow error. However, if i do `let ctx = openContext()`, it works fine. However, I am afraid this way it doesn't dispose correctly. 

Here is the error 

 Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
       ---> System.NotSupportedException:  The ReadAsync method cannot be called when another read operation is pending.
         at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
         at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|41_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
         at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|41_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.Consume(Boolean async)
         at Npgsql.NpgsqlDataReader.Close(Boolean connectionClosing, Boolean async, Boolean isDisposing)
         at Npgsql.Internal.NpgsqlConnector.CloseOngoingOperations(Boolean async)
         at Npgsql.NpgsqlConnection.CloseAsync(Boolean async)
         at Npgsql.NpgsqlConnection.Close()
         at Npgsql.NpgsqlConnection.Dispose(Boolean disposing)
         at System.ComponentModel.Component.Dispose()
         at SqlHydra.Query.QueryContext.System.IDisposable.Dispose()

**Comment by JordanMarr** [comment]
It may be related to your `Async.map` implementation.
Can you try it without `Async.map` and see if you still get the error?

**Comment by Qaysi-M** [comment]
Thank you very much for this library and your response. 

I am not used to task {}, but I did try it with async{} and it fixed it.

This code works as expected
```
let getProductChatRoomId productId personId = async {
        use ctx = openContext()
        let! a = 
            select {
                for chatRoom in Table.chatRoom do 
                where (chatRoom.product_id = Some(productId) && chatRoom.member_id = personId)
                select (chatRoom.chat_room_id)
            }
            |> ctx.ReadAsync MarketplaceDb.HydraReader.Read
            |> Async.AwaitTask
        return a |> Seq.exactlyOne
    }
```
This is though obviously is different from the Async.map, so it seems the error on my part. 

Thank you again for the help!

**Comment by JordanMarr** [comment]
Glad you are enjoying it!

This implementation of `Async.map` seems to work with your original example. 

```F#
module Async =
    let map f op = async {
        let! x = op
        let value = f x
        return value
    }
```

**Comment by Qaysi-M** [comment]
I tried your implementation, and it throws the same exception. 
I am using FsToolkit.Errorhandling Async.map, and this is their implementations 
`let inline map f x = x |> bind (f >> singleton)` . It is the same as yours I believe. 

```
module Async =
    let mapp f op = async {
        let! x = op
        let value = f x
        return value
    }

   let getProductChatRoomId' productId personId =
        use ctx = openContext()
        select {
            for chatRoom in Table.chatRoom do 
            where (chatRoom.product_id = Some(productId) && chatRoom.member_id = personId)
            select (chatRoom.chat_room_id)
        }
        |> ctx.ReadAsync MarketplaceDb.HydraReader.Read
        |> Async.AwaitTask
        |> Async.mapp(Seq.exactlyOne)
```
Then in main, 
```
[<EntryPoint>]
    let main args =
        let chatRoomId  = 
            Db.Chat.getProductChatRoomId' "someproductId" "someperosnId" 
            |> Async.RunSynchronously
        printfn "chatRoomId is %A" chatRoomId
        0 // Exit code
```
